# Generated by Django 4.2.17 on 2025-01-20 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='RLHF_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='The user prompt for which the response was given.')),
                ('response', models.TextField(help_text='The LLM response being evaluated.')),
                ('completeness_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating for completeness (1-5).')),
                ('completeness_justification', models.TextField(blank=True, help_text='Optional justification for completeness rating.', null=True)),
                ('accuracy_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating for accuracy (1-5).')),
                ('accuracy_justification', models.TextField(blank=True, help_text='Optional justification for accuracy rating.', null=True)),
                ('instruction_following_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating for instruction following (1-5).')),
                ('instruction_following_justification', models.TextField(blank=True, help_text='Optional justification for instruction following rating.', null=True)),
                ('contextual_awareness_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating for contextual awareness (1-5).')),
                ('contextual_awareness_justification', models.TextField(blank=True, help_text='Optional justification for contextual awareness rating.', null=True)),
                ('writing_quality_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating for writing quality (1-5).')),
                ('writing_quality_justification', models.TextField(blank=True, help_text='Optional justification for writing quality rating.', null=True)),
                ('creativity_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating for creativity (1-5).')),
                ('creativity_justification', models.TextField(blank=True, help_text='Optional justification for creativity rating.', null=True)),
                ('final_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Overall final score for the response (1-5).')),
                ('final_score_justification', models.TextField(blank=True, help_text='Optional justification for the final score.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time when feedback was submitted.')),
                ('user', models.ForeignKey(blank=True, help_text='User providing the feedback. Null for anonymous.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
