# Generated by Django 4.2.17 on 2025-01-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_rlhf_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RLHF_Feedback',
            new_name='RLHFFeedback',
        ),
    ]
